apiVersion: apps/v1 
kind: Deployment
metadata:
  name: front-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-api
          image: svestor/kube-tasks-app-frontend:latest
          imagePullPolicy: Always
          # env:
          # - name: TASK_ADDRESS
          #   value: "tasks-service.default:80"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "256m"
          ports:
          - containerPort: 80       
